# Generated by Django 4.2.23 on 2025-08-14 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.CreateModel(
            name='TeaacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('qualification', models.CharField(blank=True, max_length=256)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
