# Generated by Django 4.2.23 on 2025-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
