# Generated by Django 4.2.23 on 2025-08-28 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='curriculum',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
